export const breeds = [
  {
    bred_for: "Small rodent hunting, lapdog",
    breed_group: "Toy",
    height: {
      imperial: "9 - 11.5",
      metric: "23 - 29",
    },
    id: 1,
    image: {
      height: 1199,
      id: "BJa4kxc4X",
      url: "https://cdn2.thedogapi.com/images/BJa4kxc4X.jpg",
      width: 1600,
    },
    life_span: "10 - 12 years",
    name: "Affenpinscher",
    origin: "Germany, France",
    reference_image_id: "BJa4kxc4X",
    temperament: "Stubborn, Curious, Playful, Adventurous, Active, Fun-loving",
    weight: {
      imperial: "6 - 13",
      metric: "3 - 6",
    },
  },
  {
    bred_for: "Coursing and hunting",
    breed_group: "Hound",
    country_code: "AG",
    height: {
      imperial: "25 - 27",
      metric: "64 - 69",
    },
    id: 2,
    image: {
      height: 380,
      id: "hMyT4CDXR",
      url: "https://cdn2.thedogapi.com/images/hMyT4CDXR.jpg",
      width: 606,
    },
    life_span: "10 - 13 years",
    name: "Afghan Hound",
    origin: "Afghanistan, Iran, Pakistan",
    reference_image_id: "hMyT4CDXR",
    temperament: "Aloof, Clownish, Dignified, Independent, Happy",
    weight: {
      imperial: "50 - 60",
      metric: "23 - 27",
    },
  },
  {
    bred_for: "A wild pack animal",
    height: {
      imperial: "30",
      metric: "76",
    },
    id: 3,
    image: {
      height: 335,
      id: "rkiByec47",
      url: "https://cdn2.thedogapi.com/images/rkiByec47.jpg",
      width: 500,
    },
    life_span: "11 years",
    name: "African Hunting Dog",
    origin: "",
    reference_image_id: "rkiByec47",
    temperament: "Wild, Hardworking, Dutiful",
    weight: {
      imperial: "44 - 66",
      metric: "20 - 30",
    },
  },
  {
    bred_for: "Badger, otter hunting",
    breed_group: "Terrier",
    height: {
      imperial: "21 - 23",
      metric: "53 - 58",
    },
    id: 4,
    image: {
      height: 430,
      id: "1-7cgoZSh",
      url: "https://cdn2.thedogapi.com/images/1-7cgoZSh.jpg",
      width: 645,
    },
    life_span: "10 - 13 years",
    name: "Airedale Terrier",
    origin: "United Kingdom, England",
    reference_image_id: "1-7cgoZSh",
    temperament:
      "Outgoing, Friendly, Alert, Confident, Intelligent, Courageous",
    weight: {
      imperial: "40 - 65",
      metric: "18 - 29",
    },
  },
  {
    bred_for: "Sheep guarding",
    breed_group: "Working",
    height: {
      imperial: "28 - 34",
      metric: "71 - 86",
    },
    id: 5,
    image: {
      height: 471,
      id: "26pHT3Qk7",
      url: "https://cdn2.thedogapi.com/images/26pHT3Qk7.jpg",
      width: 600,
    },
    life_span: "10 - 12 years",
    name: "Akbash Dog",
    origin: "",
    reference_image_id: "26pHT3Qk7",
    temperament: "Loyal, Independent, Intelligent, Brave",
    weight: {
      imperial: "90 - 120",
      metric: "41 - 54",
    },
  },
  {
    bred_for: "Hunting bears",
    breed_group: "Working",
    height: {
      imperial: "24 - 28",
      metric: "61 - 71",
    },
    id: 6,
    image: {
      height: 853,
      id: "BFRYBufpm",
      url: "https://cdn2.thedogapi.com/images/BFRYBufpm.jpg",
      width: 1280,
    },
    life_span: "10 - 14 years",
    name: "Akita",
    reference_image_id: "BFRYBufpm",
    temperament:
      "Docile, Alert, Responsive, Dignified, Composed, Friendly, Receptive, Faithful, Courageous",
    weight: {
      imperial: "65 - 115",
      metric: "29 - 52",
    },
  },
  {
    bred_for: "Circus performer",
    breed_group: "Non-Sporting",
    country_code: "US",
    height: {
      imperial: "15 - 19",
      metric: "38 - 48",
    },
    id: 12,
    image: {
      height: 802,
      id: "Bymjyec4m",
      url: "https://cdn2.thedogapi.com/images/Bymjyec4m.jpg",
      width: 1000,
    },
    life_span: "12 - 15 years",
    name: "American Eskimo Dog",
    reference_image_id: "Bymjyec4m",
    temperament: "Friendly, Alert, Reserved, Intelligent, Protective",
    weight: {
      imperial: "20 - 40",
      metric: "9 - 18",
    },
  },
  {
    bred_for: "Companionship",
    country_code: "US",
    height: {
      imperial: "9 - 12",
      metric: "23 - 30",
    },
    id: 13,
    image: {
      height: 487,
      id: "_gn8GLrE6",
      url: "https://cdn2.thedogapi.com/images/_gn8GLrE6.jpg",
      width: 730,
    },
    life_span: "13 – 15 years",
    name: "American Eskimo Dog (Miniature)",
    reference_image_id: "_gn8GLrE6",
    temperament: "Friendly, Alert, Reserved, Intelligent, Protective",
    weight: {
      imperial: "7 - 10",
      metric: "3 - 5",
    },
  },
];
